entryPoints:
  # HTTP public
  web:
    address: ":80"
  # HTTPS public (certificat autosign√© local)
  websecure:
    address: ":443"
  # Dashboard / API Traefik
  traefik:
    address: ":8080"

api:
  dashboard: true

providers:
  # Configuration HTTP(s) dynamique (routers / services)
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
